FROM node:16.13

WORKDIR /usr/local/orchestrator

ENV PORT=80

COPY package.json package-lock.json /usr/local/orchestrator/

RUN npm install && npm cache clean --force

RUN npm install -g nodemon

COPY ./ ./

CMD ["nodemon", "app.js"]